### ISSUE TITLE
Error everytime I join a server with this mod after the update

### ISSUE THREAD

**Issue by Tofuman89** [sharkster91/SMUI#38]
Hi, I get client error every time I join a server with this mod installed after you pushed the recent update.

STACK TRACE
-----------------------------------------
Callframe at: setExclusive
function: SMUI_BodyLocations.lua -- file: SMUI_BodyLocations.lua line # 25 | MOD: Shark (and Peach's) Military Uniform Improvements

ERROR: General     , 1668733956131> 0> ExceptionLogger.logException> Exception thrown java.lang.reflect.InvocationTargetException at GeneratedMethodAccessor9.invoke.
ERROR: General     , 1668733956131> 0> DebugLogStream.printException> Stack trace:
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:188)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
	at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:76)
	at se.krka.kahlua.integration.LuaCaller.protectedCall(LuaCaller.java:117)
	at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:563)
	at zombie.Lua.LuaManager.RunLua(LuaManager.java:509)
	at zombie.Lua.LuaManager.RunLua(LuaManager.java:495)
	at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:341)
	at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:263)
	at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:390)
	at zombie.core.Core.ResetLua(Core.java:4109)
	at zombie.gameStates.ConnectToServerState.receiveServerOptions(ConnectToServerState.java:131)
	at zombie.gameStates.ConnectToServerState.Finish(ConnectToServerState.java:688)
	at zombie.gameStates.ConnectToServerState.update(ConnectToServerState.java:100)
	at zombie.gameStates.MainScreenState.update(MainScreenState.java:523)
	at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
	at zombie.GameWindow.logic(GameWindow.java:298)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:765)
	at zombie.GameWindow.run_ez(GameWindow.java:681)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: unknown location "SLEOJumpsuitPlus"
	at zombie.characters.WornItems.BodyLocationGroup.getLocationNotNull(BodyLocationGroup.java:29)
	at zombie.characters.WornItems.BodyLocationGroup.setExclusive(BodyLocationGroup.java:55)
	... 31 more

**Comment by sharkster91** [comment]
Thanks, this was binded wrong. I am fixing this now.

**Comment by Tofuman89** [comment]
Thank you for the prompt fix. Cheers
