### ISSUE TITLE
Getting errors with just sharks law enforcement turned on

### ISSUE THREAD

**Issue by vinilol467** [sharkster91/SMUI#48]
So, i was having issues with a modpack i made, and i after some testing i found out: Shark's law enforcement was the one causing the errors. But to my surprise it was not a incompability with another mod, because when i tried it alone, still got the error message. 
![image](https://user-images.githubusercontent.com/118195842/204033910-b133d27e-8764-4ac3-a308-a3ff6dca0de1.png) .
the build im playing is 41.78.12. one of the errors:
SEVERE: Error found in LUA file: C:\Program Files (x86)\Steam\steamapps\workshop\content\108600\2616752828\mods\Shark's Law Enforcement Overhaul\media\maps\SLEOSpawn\objects.lua
ERROR: General     , 1669424000086> ExceptionLogger.logException> Exception thrown se.krka.kahlua.vm.KahluaException: C:\Program Files (x86)\Steam\steamapps\workshop\content\108600\2616752828\mods\Shark's Law Enforcement Overhaul\media\maps\SLEOSpawn\objects.lua:2: '}' expected near `4846` at LexState.lexerror line:278.
ERROR: General     , 1669424000086> DebugLogStream.printException> Stack trace:
se.krka.kahlua.vm.KahluaException: C:\Program Files (x86)\Steam\steamapps\workshop\content\108600\2616752828\mods\Shark's Law Enforcement Overhaul\media\maps\SLEOSpawn\objects.lua:2: '}' expected near `4846`
	at org.luaj.kahluafork.compiler.LexState.lexerror(LexState.java:278)
	at org.luaj.kahluafork.compiler.LexState.syntaxerror(LexState.java:289)
	at org.luaj.kahluafork.compiler.LexState.error_expected(LexState.java:683)
	at org.luaj.kahluafork.compiler.LexState.check_match(LexState.java:713)
	at org.luaj.kahluafork.compiler.LexState.constructor(LexState.java:962)
	at org.luaj.kahluafork.compiler.LexState.simpleexp(LexState.java:1202)
	at org.luaj.kahluafork.compiler.LexState.subexpr(LexState.java:1303)
	at org.luaj.kahluafork.compiler.LexState.expr(LexState.java:1321)
	at org.luaj.kahluafork.compiler.LexState.listfield(LexState.java:919)
	at org.luaj.kahluafork.compiler.LexState.constructor(LexState.java:957)
	at org.luaj.kahluafork.compiler.LexState.simpleexp(LexState.java:1202)
	at org.luaj.kahluafork.compiler.LexState.subexpr(LexState.java:1303)
	at org.luaj.kahluafork.compiler.LexState.expr(LexState.java:1321)
	at org.luaj.kahluafork.compiler.LexState.explist1(LexState.java:1036)
	at org.luaj.kahluafork.compiler.LexState.assignment(LexState.java:1403)
	at org.luaj.kahluafork.compiler.LexState.exprstat(LexState.java:1696)
	at org.luaj.kahluafork.compiler.LexState.statement(LexState.java:1779)
	at org.luaj.kahluafork.compiler.LexState.chunk(LexState.java:1790)
	at org.luaj.kahluafork.compiler.LexState.compile(LexState.java:198)
	at se.krka.kahlua.luaj.compiler.LuaCompiler.loadis(LuaCompiler.java:132)
	at se.krka.kahlua.luaj.compiler.LuaCompiler.loadis(LuaCompiler.java:124)
	at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:546)
	at zombie.Lua.LuaManager.RunLua(LuaManager.java:510)
	at zombie.Lua.LuaManager$GlobalObject.reloadLuaFile(LuaManager.java:2110)
	at jdk.internal.reflect.GeneratedMethodAccessor336.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:188)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:65)
	at zombie.iso.IsoWorld.init(IsoWorld.java:2475)
	at zombie.gameStates.GameLoadingState$1.runInner(GameLoadingState.java:268)
	at zombie.gameStates.GameLoadingState$1.run(GameLoadingState.java:225)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by theernestrain** [comment]
I am receiving same error
