### ISSUE TITLE
Manage Containers throwing errors and no longer functioning after update

### ISSUE THREAD

**Issue by Drbbeard** [sharkster91/SMUI#66]
Either coincidence or issue. The Manage Containers mod functions as normal in both single and multiplayer unless this add-on is enabled. This started with the most recent update to this mod. No other changes have been made on my server. Have been using both with no issue for weeks.

**Comment by sharkster91** [comment]
I know exactly what is causing this. The decision to pull it and
reintroduce the bug it fixes to make the mod compatible with other mods I
have zero experience or knowledge of is another thing.

**Comment by SleepVR6** [comment]
So if we're experiencing this issue? The only solution is to stop using the mod?

**Comment by sharkster91** [comment]
For now, yes. I'll try to find a friendlier solution because the
alternative is that I just let SMUI + every other clothing mod people have
that is also installed just completely stall out the game when you try to
tear/make a sheet rope. I will make a decision in the morning.

**Comment by ottenheimer** [comment]
Is this the same error your experiencing?

function: DetectContainers -- file: placeInContainers.lua line # 15 | MOD: Manage Containers
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@5f061210
function: createMenu -- file: SMUI_InventoryPaneContextMenuFix.lua line # 787 | MOD: Shark (and Peach's) Military Uniform Improvements
function: onRightMouseUp -- file: ISInventoryPane.lua line # 1422 | MOD: Let Me Think
java.lang.RuntimeException: Object tried to call nil in DetectContainers
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:973)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
    at zombie.Lua.LuaEventManager.triggerEventGarbage(LuaEventManager.java:186)
    at zombie.Lua.LuaManager$GlobalObject.triggerEvent(LuaManager.java:3080)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
    at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
    at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:60)
    at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallBoolean(KahluaThread.java:1924)
    at se.krka.kahlua.integration.LuaCaller.protectedCallBoolean(LuaCaller.java:104)
    at zombie.ui.UIElement.onRightMouseUp(UIElement.java:1458)
    at zombie.ui.UIElement.onRightMouseUp(UIElement.java:1416)
    at zombie.ui.UIManager.update(UIManager.java:910)
    at zombie.GameWindow.logic(GameWindow.java:262)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
